const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const header = key => page.locator(`th[data-column="${key}"] .column-label`);
  const values = key => page.locator(`tbody td[data-column="${key}"]`).allTextContents();
  try {
    await page.goto(`${process.env.CTFD_URL || 'http://localhost:8000'}/login`);
    await page.locator('#name').fill('player');
    await page.locator('#password').fill('express-player-local');
    await page.locator('#_submit').click();
    await page.goto(`${process.env.CTFD_URL || 'http://localhost:8000'}/challenges`);
    await page.locator('tbody tr').first().waitFor();
    await header('points').click();
    const points = (await values('points')).map(Number);
    assert(points.length >= 3);
    assert.deepEqual(points, [...points].sort((a, b) => a - b));
    await page.keyboard.press('Enter');
    assert.deepEqual((await values('points')).map(Number), [...points].sort((a, b) => b - a));
    await page.locator('#search').fill('Welcome');
    await page.locator('#search').fill('');
    assert.deepEqual((await values('points')).map(Number), [...points].sort((a, b) => b - a));
    await header('subject').click();
    const names = await values('subject');
    assert.deepEqual(names, [...names].sort(new Intl.Collator(undefined, { numeric: true, sensitivity: 'base' }).compare));
    const source = await header('subject').boundingBox();
    const target = await header('category').boundingBox();
    await page.mouse.move(source.x + 30, source.y + source.height / 2);
    await page.mouse.down();
    await page.mouse.move(target.x + target.width / 2, target.y + target.height / 2, { steps: 8 });
    await page.locator('.column-drag-ghost').waitFor();
    assert.equal(await page.locator('th.column-drop-after').count(), 1);
    await page.screenshot({ path: 'dev/screenshots/columns-drag.png' });
    await page.mouse.up();
    assert.deepEqual(await page.locator('thead th').evaluateAll(cells => cells.map(cell => cell.dataset.column)), ['status', 'category', 'subject', 'points']);
    assert.equal(await page.locator('th[data-column="subject"]').getAttribute('aria-sort'), 'ascending');
    assert.deepEqual(await values('subject'), names);
    assert.equal(await page.locator('.column-drag-ghost').count(), 0);
    await header('status').click();
    const states = await page.locator('tbody tr').evaluateAll(rows => rows.map(row => Number(row.classList.contains('read'))));
    assert.deepEqual(states, [...states].sort());
    await page.setViewportSize({ width: 390, height: 844 });
    await page.reload();
    await page.locator('tbody tr').first().waitFor();
    await header('points').click();
    assert.deepEqual((await values('points')).map(Number), [...points].sort((a, b) => a - b));
    assert.deepEqual(errors, []);
    console.log('PASS: numeric/text/status sorting, keyboard sort, search retention, drag preview/drop marker, reorder without sorting, cleanup and mobile sorting');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
