const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    const user = `unread-${Date.now()}`;
    await page.goto(`${process.env.CTFD_URL || 'http://localhost:8000'}/register`);
    await page.locator('[name=name]').fill(user);
    await page.locator('[name=email]').fill(`${user}@example.test`);
    await page.locator('[name=password]').fill('express-browser-test');
    await page.locator('[type=submit]').click();
    await page.waitForURL('**/challenges');
    await page.locator('.open-challenge').first().waitFor();
    assert.equal(await page.locator('#address').innerText(), 'Folders / All Challenges');
    assert.deepEqual(await page.locator('#folders').evaluate(el => [...el.children].slice(0,3).map(child => child.dataset.view || child.tagName)), ['all','unread','HR']);
    const before = await page.locator('.express-window').boundingBox();
    const handle = await page.locator('.window-drag-handle').boundingBox();
    await page.mouse.move(handle.x + 100, handle.y + 10);
    await page.mouse.down();
    await page.mouse.move(handle.x + 110, handle.y + 20, { steps: 5 });
    await page.mouse.up();
    const after = await page.locator('.express-window').boundingBox();
    assert(Math.abs(after.x - before.x - 10) < 1 && Math.abs(after.y - before.y - 10) < 1);
    await page.locator('#folders [data-view=unread]').click();
    assert.equal(await page.locator('#address').innerText(), 'Folders / Unsolved Challenges');
    const count = await page.locator('.open-challenge').count();
    const welcome = page.getByRole('button', { name: 'Welcome to your inbox', exact: true });
    await welcome.click();
    await page.locator('#flag').waitFor();
    assert.equal(await page.locator('#address').innerText(), 'Folders / Unsolved Challenges');
    await page.locator('#back').click();
    assert.equal(await page.locator('.open-challenge').count(), count);
    await welcome.click();
    await page.locator('#flag').fill('flag{youve_got_mail}');
    await page.getByRole('button', { name: 'Send', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#reader').hidden);
    assert.equal(await page.locator('.open-challenge').count(), count - 1);
    assert.equal(await welcome.count(), 0);
    await page.locator('#all-challenges').click();
    assert.equal(await welcome.count(), 1);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(100);
    const rect = await page.locator('.express-window').boundingBox();
    assert(rect.x >= 0 && rect.y >= 0 && rect.x + rect.width <= 391 && rect.y + rect.height <= 845);
    assert.equal(await page.locator('.express-search .fa-search').isVisible(), true);
    assert(await page.locator('.express-search').evaluate(element => {
      const input = element.querySelector('input');
      const icon = element.querySelector('i').getBoundingClientRect();
      const textStart = input.getBoundingClientRect().left + parseFloat(getComputedStyle(input).paddingLeft);
      return textStart >= icon.right + 4;
    }), 'Search text must leave a gap after the magnifying glass');
    await page.screenshot({ path: 'dev/screenshots/unread-mobile.png' });
    assert.deepEqual(errors, []);
    console.log('PASS: folder order, unread opening/solve/removal, address breadcrumb, main window movement and mobile boundaries/search icon');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
