import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

export default defineConfig({
  plugins: [svelte(), {
    name: 'ctfd-script-template',
    writeBundle(_, bundle) {
      const entry = Object.values(bundle).find(file => file.type === 'chunk' && file.isEntry);
      const version = createHash('sha256').update(entry.code).digest('hex').slice(0, 12);
      writeFileSync('theme/templates/components/challenges-script.html',
        `{# Generated by npm run build. #}\n<script type="module" src="{{ request.script_root }}/themes/challenge-express/static/dist/${entry.fileName}?v=${version}"></script>\n`);
    }
  }],
  build: {
    outDir: 'theme/static/dist',
    emptyOutDir: true,
    lib: { entry: 'frontend/main.js', formats: ['es'], fileName: () => 'challenges.js' },
    minify: true
  }
});
